#!/bin/bash

#FILES="forecast_hour_by_hour.xml forecast.xml"
FILES="/tmp/f1 /tmp/f2"
rm -f $FILES

wget http://www.yr.no/place/United_States/New_York/Tarrytown/forecast_hour_by_hour.xml -O /tmp/f1 >/dev/null 2>&1
wget http://www.yr.no/place/United_States/New_York/Tarrytown/forecast.xml -O /tmp/f2 >/dev/null 2>&1

NAME=`cat $FILES | grep symbol | cut -d '"' -f 6 | sed s/\ /_/g`
CELSIUS=`cat $FILES | grep celsius | cut -d '"' -f 4`
PRECIP=`cat $FILES | grep precipitation | cut -d '"' -f 2`
TIME=`cat $FILES | grep "time from" | cut -d '"' -f 2`

i=1
for t in $TIME; do
    N=`echo $NAME | cut -d ' ' -f $i`
    C=`echo $CELSIUS | cut -d ' ' -f $i`
    P=`echo $PRECIP | cut -d ' ' -f $i`
    F=`echo "(($C * 1.8) + 32)" | bc`
    D=`date -d "$t"`
    echo -e "$t $F $P $N"

    i=$((i+1))
done | sort -rn |uniq > /tmp/forecast

cat /tmp/forecast | while read l; do
    t=`echo $l |cut -d ' ' -f 1`
    D=`date -d "$t" +"%a %_I%P"`
    echo -en "$D\t"
    echo $l | cut -d ' ' -f 2- | sed s/" "/"\t"/g
done


